/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface GameTile {
        "isPlayerOnTile": boolean;
        "onTileEnter": () => void;
        "x": number;
        "y": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PlayerAvatar {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGameTileElement extends Components.GameTile, HTMLStencilElement {
    }
    var HTMLGameTileElement: {
        prototype: HTMLGameTileElement;
        new (): HTMLGameTileElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPlayerAvatarElement extends Components.PlayerAvatar, HTMLStencilElement {
    }
    var HTMLPlayerAvatarElement: {
        prototype: HTMLPlayerAvatarElement;
        new (): HTMLPlayerAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "game-tile": HTMLGameTileElement;
        "my-component": HTMLMyComponentElement;
        "player-avatar": HTMLPlayerAvatarElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface GameTile {
        "isPlayerOnTile"?: boolean;
        "onTileEnter"?: () => void;
        "x"?: number;
        "y"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PlayerAvatar {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "game-tile": GameTile;
        "my-component": MyComponent;
        "player-avatar": PlayerAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "game-tile": LocalJSX.GameTile & JSXBase.HTMLAttributes<HTMLGameTileElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "player-avatar": LocalJSX.PlayerAvatar & JSXBase.HTMLAttributes<HTMLPlayerAvatarElement>;
        }
    }
}
